language: php

php:
  - 7.3

addons:
  chrome: stable
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_install:
  - composer self-update
  - cp .env.travis .env
  - psql -c 'create database travis_ci_test;' -U postgres

install:
  - pecl install trader
  - composer install --no-interaction

before_script:
  - php artisan key:generate
  - php artisan migrate
  - php artisan dusk:chrome-driver
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit

after_success:
  - |
    if [ $TRAVIS_BRANCH == "master" ]; then
      curl https://forge.laravel.com/servers/382754/sites/1073111/deploy/http?token=D2vtUsE6S4sOCeXlWSeB071mJFS9qq3wY3m8shKs
    fi

cache:
  directories:
    - node_modules
    - vendor
